[2022-05-11 00:03:52,954] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-05-10T00:00:00+00:00 [queued]>
[2022-05-11 00:03:53,045] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-05-10T00:00:00+00:00 [queued]>
[2022-05-11 00:03:53,049] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 00:03:53,053] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-11 00:03:53,057] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 00:03:53,170] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): accurate> on 2022-05-10 00:00:00+00:00
[2022-05-11 00:03:53,190] {standard_task_runner.py:52} INFO - Started process 10657 to run task
[2022-05-11 00:03:53,228] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2022-05-10T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpyn_e549w', '--error-file', '/tmp/tmp4mvz84mz']
[2022-05-11 00:03:53,232] {standard_task_runner.py:80} INFO - Job 39: Subtask accurate
[2022-05-11 00:03:53,601] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2022-05-10T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-11 00:03:53,965] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-10T00:00:00+00:00
[2022-05-11 00:03:53,980] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-11 00:03:53,986] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-05-11 00:03:54,060] {subprocess.py:85} INFO - Output:
[2022-05-11 00:03:54,071] {subprocess.py:89} INFO - accurate
[2022-05-11 00:03:54,075] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-11 00:03:54,229] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220510T000000, start_date=20220511T000352, end_date=20220511T000354
[2022-05-11 00:03:54,341] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-11 00:03:54,505] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
