[2022-05-12 12:00:13,248] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-05-12 12:00:13,273] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-05-12 12:00:13,274] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 12:00:13,276] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-12 12:00:13,282] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 12:00:13,304] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): training_model_A> on 2022-05-11 00:00:00+00:00
[2022-05-12 12:00:13,316] {standard_task_runner.py:52} INFO - Started process 16031 to run task
[2022-05-12 12:00:13,330] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_A', 'scheduled__2022-05-11T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpoc1c0vg9', '--error-file', '/tmp/tmpz3_qdq42']
[2022-05-12 12:00:13,336] {standard_task_runner.py:80} INFO - Job 41: Subtask training_model_A
[2022-05-12 12:00:13,586] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.training_model_A scheduled__2022-05-11T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-12 12:00:13,826] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-11T00:00:00+00:00
[2022-05-12 12:00:13,830] {python.py:175} INFO - Done. Returned value was: 4
[2022-05-12 12:00:14,024] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20220511T000000, start_date=20220512T120013, end_date=20220512T120014
[2022-05-12 12:00:14,093] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-12 12:00:14,181] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
