[2022-04-11 00:00:04,069] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-04-10T00:00:00+00:00 [queued]>
[2022-04-11 00:00:04,081] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-04-10T00:00:00+00:00 [queued]>
[2022-04-11 00:00:04,082] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 00:00:04,083] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-11 00:00:04,083] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 00:00:04,096] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): accurate> on 2022-04-10 00:00:00+00:00
[2022-04-11 00:00:04,101] {standard_task_runner.py:52} INFO - Started process 13416 to run task
[2022-04-11 00:00:04,105] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2022-04-10T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpr1m_2g_u', '--error-file', '/tmp/tmp42h7iqrt']
[2022-04-11 00:00:04,106] {standard_task_runner.py:80} INFO - Job 17: Subtask accurate
[2022-04-11 00:00:04,171] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2022-04-10T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-04-11 00:00:04,227] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-04-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-10T00:00:00+00:00
[2022-04-11 00:00:04,229] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-11 00:00:04,230] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-04-11 00:00:04,242] {subprocess.py:85} INFO - Output:
[2022-04-11 00:00:04,244] {subprocess.py:89} INFO - accurate
[2022-04-11 00:00:04,245] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-11 00:00:04,271] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220410T000000, start_date=20220411T000004, end_date=20220411T000004
[2022-04-11 00:00:04,320] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 00:00:04,348] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
