[2022-05-12 12:00:15,952] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-05-12 12:00:15,975] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-05-12 12:00:15,977] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 12:00:15,978] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-12 12:00:15,979] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 12:00:16,004] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): accurate> on 2022-05-11 00:00:00+00:00
[2022-05-12 12:00:16,014] {standard_task_runner.py:52} INFO - Started process 16036 to run task
[2022-05-12 12:00:16,035] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2022-05-11T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpto_bg0rt', '--error-file', '/tmp/tmpwb5ybr2r']
[2022-05-12 12:00:16,037] {standard_task_runner.py:80} INFO - Job 44: Subtask accurate
[2022-05-12 12:00:16,150] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2022-05-11T00:00:00+00:00 [running]> on host c0c6f6bf1c08
[2022-05-12 12:00:16,248] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-11T00:00:00+00:00
[2022-05-12 12:00:16,250] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 12:00:16,253] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-05-12 12:00:16,279] {subprocess.py:85} INFO - Output:
[2022-05-12 12:00:16,294] {subprocess.py:89} INFO - accurate
[2022-05-12 12:00:16,295] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-12 12:00:16,333] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220511T000000, start_date=20220512T120015, end_date=20220512T120016
[2022-05-12 12:00:16,403] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-12 12:00:16,448] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
